#python 2.7.15
from datetime import datetime
import time
import calendar
print "----BANk CODE------"
time.sleep(2)
print("########CARREGANDO####")
time.sleep(3)
print ("forneca seus codigo de login")
input("digite seu codigo")
print("codigo ok")
time.sleep(3)
print ("VAMOS CARREGAR SERVIDOR?")
time.sleep (2)
print ("escolha um servidor digitando numero")
print ("Servidor Brasil 1")
print ("Servidor Canada 2")
time.sleep(3)
input("Digite um numero")
time.sleep(2)
print ("Servidor escolhido com sucesso")
time.sleep(3)
print ("agora aguarde carregamento")
time.sleep(2)
print("carregando 1%")
time.sleep(4)
print("carregando 2%")
time.sleep(4)
print("carregando 3%")
time.sleep (1)
print("carregando 20%")
time.sleep(1)
print("carregando 30%")
time.sleep(4)
print("carregando 50%")
time.sleep(7)
print("carregando 100%")
time.sleep(4)
print ("digite (1) para banco brasil")
input("Qual Banco ")
time.sleep(4)
print("seu dados sao")
print("Conta Corrente")
print ("69123-2")
print ("Agencia")
print ("7018")
print ("Cidade")
print ("Campinas")
print ("Estado")
print ("sp")
time.sleep(1)
print("conta 2")
time.sleep(6)
print ("conta qui")
time.sleep(3)
print ("FINALIZANDO COM SUCESSO")
time.sleep(6)
print ("Gerador feito by paulo antonio")
